#pragma once

/// @file rxs_api.h
/// @brief RXS Toolkit Modern C++ API (namespace rxs)
/// @author Suzhou Ruixin Vision Technology Co., Ltd.
/// @date 2026-06-29
///
/// This header provides a clean, namespace-scoped API layer over the legacy
/// czxToolkit DLL exports. It enables type-safe usage without GetProcAddress
/// boilerplate and serves as the migration path toward a header-only library.
///
/// ## Usage — Static Link (recommended for new code)
/// ```cpp
/// #include <rxs/rxs_api.h>
/// auto result = rxs::fitBSpline(cloud);
/// ```
/// Link against czxToolkit.lib (import library generated by CMake).
///
/// ## Usage — Dynamic Link via ToolkitHandle (backward compatibility)
/// ```cpp
/// #include <rxs/rxs_api.h>
/// rxs::ToolkitHandle toolkit;
/// if (toolkit.load("czxToolkit.dll")) {
///     auto result = toolkit.fitBSpline(cloud);
/// }
/// ```

#include <vector>
#include <string>
#include <memory>
#include <cstdint>
#include <functional>
#include <map>

#include <Eigen/Dense>
#include <pcl/point_types.h>
#include <pcl/point_cloud.h>

#include "rxs_export.h"

// Forward-declare OpenCV types used in the photometric stereo API
namespace cv { class Mat; }

/// @brief RXS Vision namespace
namespace rxs {

// ---------------------------------------------------------------------------
// Type aliases — mirror legacy typedefs (types_.h / czxTool.h)
// ---------------------------------------------------------------------------
using PointT = pcl::PointXYZ;
using CloudT = pcl::PointCloud<PointT>;
using CloudPtr = CloudT::Ptr;

/// @brief Region-of-interest bounding box (replaces legacy 4-double params)
struct BaseFace {
    double min_x = 0;
    double max_x = 0;
    double min_y = 0;
    double max_y = 0;
};

/// @brief Flatness result with extreme points
struct FlatnessResult {
    float value = 0.0f;       ///< Flatness value (mm)
    PointT min_point;         ///< Lowest point on fitted plane
    PointT max_point;         ///< Highest point on fitted plane
};

/// @brief Keyboard / button feature extraction result
struct KeyboardResult {
    std::vector<CloudPtr> planes;              ///< Extracted plane point clouds
    std::vector<std::vector<float>> flatness;  ///< Flatness per verify-region per plane
    Eigen::MatrixXf offset;                    ///< Inter-plane offset matrix
};

/// @brief Laptop type enumeration (mirrors LaptopLine::LaptopType)
enum class LaptopType : int {
    BlueLaptopWithHoles   = 0,  ///< 带网孔蓝色笔记本
    BlueLaptop            = 1,  ///< 蓝色笔记本
    Keyboard              = 2,  ///< 键盘
    AssembledKeyboard     = 3,  ///< 装配键盘
    AssembledBackplate    = 4,  ///< 装配背板
    AssembledBackplatePre = 5,  ///< 装配背板_普雷茨特
    AssembledKeyboardPre  = 6,  ///< 装配键盘_普雷茨特
    NB6767D_GYG9D         = 7,  ///< NB6767D_GYG9D
    NB6837A               = 8,  ///< NB6837A
    IDC40                 = 9,  ///< IDC40
    IDC401X               = 10, ///< IDC401X
};

/// @brief Photometric stereo output mode
enum class PhotometricMode : int {
    Albedo  = 0,  ///< Reflectance map (default)
    Normal  = 1,  ///< Surface normal map
    Gray    = 2,  ///< Grayscale normal visualization
    Heights = 3,  ///< Height map (global integration)
};

// ===========================================================================
//  Algorithm API
// ===========================================================================

// ---------------------------------------------------------------------------
/// @defgroup curve Curve Fitting
// ---------------------------------------------------------------------------

/// @brief B-spline curve fitting
/// @param cloud Input point cloud
/// @param visual Enable debug visualization (default: false)
/// @return [arc_length, projection_length, profile_deviation]
RXS_API std::vector<double> fitBSpline(CloudPtr cloud, bool visual = false);

// ---------------------------------------------------------------------------
/// @defgroup feature Feature Measurement
// ---------------------------------------------------------------------------

/// @brief Semiconductor feature measurement
/// @param cloud Input point cloud
/// @param roi Region of interest bounding box
/// @return Detected feature points (ball centers)
RXS_API std::vector<PointT> semiconductor(CloudPtr cloud, const BaseFace& roi);

/// @brief PIN pin measurement
/// @param cloud Input point cloud
/// @param roi Region of interest bounding box
/// @return Detected PIN positions (highest points)
RXS_API std::vector<PointT> measurePIN(CloudPtr cloud, const BaseFace& roi);

/// @brief Keyboard / button feature extraction
/// @param cloud Input point cloud
/// @param initial_plane_pos Path to initial plane position config file
/// @param verify_paths Paths to verification region config files
/// @return Struct containing planes, flatness values, and offset matrix
RXS_API KeyboardResult keyboard(CloudPtr cloud,
                                const std::string& initial_plane_pos,
                                const std::vector<std::string>& verify_paths);

/// @brief Surface profile measurement
/// @param cloud Input point cloud
/// @param zone_num Number of zones for OMP surface analysis (default: 12)
/// @return Surface profile deviation (mm), -1 if insufficient points
RXS_API double surfaceProfile(CloudPtr cloud, int zone_num = 12);

/// @brief Volume calculation
/// @param cloud Input point cloud
/// @param xyInterval Grid interval in XY plane (default: 12.0)
/// @return Volume (sum of z * xyInterval^2)
RXS_API double volume(CloudPtr cloud, double xyInterval = 12.0);

/// @brief Flatness calculation (least-squares plane fit + peak-to-valley)
/// @param cloud Input plane point cloud
/// @return Flatness result with value and extreme points
RXS_API FlatnessResult flatness(CloudPtr cloud);

// ---------------------------------------------------------------------------
/// @defgroup registration Registration
// ---------------------------------------------------------------------------

/// @brief Point cloud registration via 3-hole center matching + SVD
/// @param source Source point cloud
/// @param target Target point cloud
/// @param hole_pos_x Path to X-axis hole position file
/// @param hole_pos_y Path to Y-axis hole position file
/// @return 4x4 transformation matrix (source → target)
/// @note After the call, source and target are replaced with 3-point hole centers
RXS_API Eigen::Matrix4f registration(CloudPtr source, CloudPtr target,
                                     const std::string& hole_pos_x,
                                     const std::string& hole_pos_y);

/// @brief Apply 4x4 transformation to point cloud
/// @param cloud Point cloud to transform
/// @param transform 4x4 transformation matrix
/// @return Transformed point cloud (new allocation)
RXS_API CloudPtr rtConvert(CloudPtr cloud, const Eigen::Matrix4f& transform);

// ---------------------------------------------------------------------------
/// @defgroup hull Convex Hull
// ---------------------------------------------------------------------------

/// @brief Compute 3D convex hull (PCL wrapper)
/// @param cloud Input point cloud
/// @return Convex hull vertex point cloud
RXS_API CloudPtr computeConvexHull(CloudPtr cloud);

// ---------------------------------------------------------------------------
/// @defgroup deformation Deformation & Laptop
// ---------------------------------------------------------------------------

/// @brief Initialize naked model for deformation calculation
/// @param model Reference model point cloud
RXS_API void initModelNake(CloudPtr model);

/// @brief Compute deformation (naked model mode)
/// @param model Reference model point cloud (must be initialized first)
/// @param cloud Measured point cloud
/// @return [deformation, sharpness, 2D_length, left_gap, right_gap, ...]
///         Values of -1 indicate failed calculation.
RXS_API std::vector<float> computeDeformationNake(CloudPtr model, CloudPtr cloud);

/// @brief Full laptop calculation (init + deform in one call)
/// @param model Reference model point cloud
/// @param cloud Measured point cloud
/// @param type Laptop type enumeration
/// @return [deformation, sharpness, 2D_length, left_gap, right_gap, ...]
///         Values of -1 indicate failed calculation.
RXS_API std::vector<float> laptopCalculation(CloudPtr model, CloudPtr cloud,
                                             LaptopType type);

// ---------------------------------------------------------------------------
/// @defgroup distance Distance Calculation
// ---------------------------------------------------------------------------

/// @brief Dis2Dis distance calculation
/// @param model Reference model point cloud
/// @param source Source point cloud to measure
/// @param interval_x Model point cloud X-axis sampling interval
/// @param interval_y Model point cloud Y-axis sampling interval
/// @return Distance vector (one per source point)
RXS_API std::vector<float> dis2dis(CloudPtr model, CloudPtr source,
                                   float interval_x = 20.0f,
                                   float interval_y = 20.0f);

// ---------------------------------------------------------------------------
/// @defgroup color Color Recognition
// ---------------------------------------------------------------------------

/// @brief Color registration / recognition
/// @param model_root Path to model directory (subdirs named by color)
/// @param object_directory Path to object image directory
/// @return Predicted color name
RXS_API std::string colorReg(const std::string& model_root,
                             const std::string& object_directory);

// ---------------------------------------------------------------------------
/// @defgroup photometric Photometric Stereo
// ---------------------------------------------------------------------------

/// @brief Photometric stereo reconstruction
/// @param imgs Input images (one per light direction)
/// @param slants Slant angles (angle between light and camera)
/// @param tilts Tilt angles (angle between light and X-axis)
/// @param mode Output mode (Albedo / Normal / Gray / Heights)
/// @return Output image (cv::Mat)
/// @note Requires OpenCV. For CUDA acceleration, build with RXS_BUILD_CUDA=ON.
RXS_API cv::Mat photometricStero(const std::vector<cv::Mat>& imgs,
                                 const std::vector<float>& slants,
                                 const std::vector<float>& tilts,
                                 PhotometricMode mode = PhotometricMode::Albedo);

// ===========================================================================
//  ToolkitHandle — Dynamic Loading (backward compatibility)
// ===========================================================================

/// @brief Toolkit handle for DLL-based dynamic loading
///
/// This class wraps LoadLibrary/GetProcAddress for consumers that cannot
/// (or prefer not to) link against the import library at compile time.
/// It provides type-safe convenience methods for all 18 legacy exports.
///
/// Usage:
/// ```cpp
/// rxs::ToolkitHandle toolkit;
/// if (!toolkit.load("czxToolkit.dll")) {
///     std::cerr << "Failed to load DLL\n";
///     return;
/// }
/// auto result = toolkit.fitBSpline(cloud, false);
/// ```
class RXS_API ToolkitHandle {
public:
    ToolkitHandle();
    ~ToolkitHandle();

    ToolkitHandle(const ToolkitHandle&) = delete;
    ToolkitHandle& operator=(const ToolkitHandle&) = delete;
    ToolkitHandle(ToolkitHandle&&) noexcept;
    ToolkitHandle& operator=(ToolkitHandle&&) noexcept;

    /// @brief Load the czxToolkit DLL
    /// @param dll_path Path to czxToolkit.dll (default: search system path)
    /// @return true if loaded successfully
    bool load(const std::string& dll_path = "czxToolkit.dll");

    /// @brief Unload the DLL and release all function pointers
    void unload();

    /// @brief Check if the DLL is loaded
    bool isLoaded() const;

    /// @brief Check if a specific exported function is available
    /// @param func_name Function name to check (as exported in Source.def)
    /// @return true if the function exists in the loaded DLL
    bool hasFunction(const std::string& func_name) const;

    /// @brief Get raw function pointer by name
    /// @param func_name Exported function name
    /// @return Function pointer, or nullptr if not found / not loaded
    void* getFunction(const std::string& func_name) const;

    /// @brief Get list of all known exported function names
    /// @return Vector of the 18 legacy export names
    static std::vector<std::string> getExportedFunctionNames();

    // -----------------------------------------------------------------------
    // Convenience methods — one per legacy export
    // -----------------------------------------------------------------------

    std::vector<double> fitBSpline(CloudPtr cloud, bool visual = false);
    std::vector<PointT> semiconductor(CloudPtr cloud, const BaseFace& roi);
    std::vector<PointT> measurePIN(CloudPtr cloud, const BaseFace& roi);
    Eigen::Matrix4f registration(CloudPtr source, CloudPtr target,
                                 const std::string& hole_pos_x,
                                 const std::string& hole_pos_y);
    KeyboardResult keyboard(CloudPtr cloud,
                            const std::string& initial_plane_pos,
                            const std::vector<std::string>& verify_paths);
    double surfaceProfile(CloudPtr cloud, int zone_num = 12);
    CloudPtr computeConvexHull(CloudPtr cloud);
    double volume(CloudPtr cloud, double xyInterval = 12.0);
    void initModelNake(CloudPtr model);
    std::vector<float> computeDeformationNake(CloudPtr model, CloudPtr cloud);
    std::vector<float> laptopCalculation(CloudPtr model, CloudPtr cloud,
                                         LaptopType type);
    std::vector<float> dis2dis(CloudPtr model, CloudPtr source,
                               float interval_x = 20.0f,
                               float interval_y = 20.0f);
    std::string colorReg(const std::string& model_root,
                         const std::string& object_directory);
    FlatnessResult flatness(CloudPtr cloud);
    CloudPtr rtConvert(CloudPtr cloud, const Eigen::Matrix4f& transform);

private:
    struct Impl;
    std::unique_ptr<Impl> pimpl;
};

} // namespace rxs
